//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jelo
    {
        public int Id { get; set; }


        [Display(Name = "Naziv jela")]
        public string Naziv { get; set; }

        [Display(Name = "Cijena jela")]
        public Nullable<decimal> Cijena { get; set; }
        [Display(Name = "Naziv restorana")]
        public Nullable<int> RestoranID { get; set; }
        
        public virtual Restoran Restoran { get; set; }
    }
}
